.gitignore
CONTRIBUTING.md
LICENSE
pom.xml
trust-store-loader/README.md
trust-store-loader/pom.xml
trust-store-loader/src/main/java/uk/gov/pay/commons/truststoreloader/TrustStoreLoader.java
trust-store-loader/src/main/java/uk/gov/pay/commons/truststoreloader/TrustingSSLSocketFactory.java
trust-store-loader/src/test/java/uk/gov/pay/commons/truststoreloader/TrustStoreLoaderTest.java

Initial docs along with the trust store loader module
Added a simple test just to make sure the key class is invoked, however it is not testing with any sample certificates loaded. Quite cumbersome to do such a test, but this works in all java apps at the moment.

PP-2591 commons trust store

---

pom.xml
transaction-flow/README.md
transaction-flow/pom.xml
transaction-flow/src/main/java/uk/gov/pay/commons/transactionflow/TransactionContext.java
transaction-flow/src/main/java/uk/gov/pay/commons/transactionflow/TransactionFlow.java
transaction-flow/src/main/java/uk/gov/pay/commons/transactionflow/TransactionalException.java
transaction-flow/src/main/java/uk/gov/pay/commons/transactionflow/operations/ManagedOperation.java
transaction-flow/src/main/java/uk/gov/pay/commons/transactionflow/operations/NonTransactionalOperation.java
transaction-flow/src/main/java/uk/gov/pay/commons/transactionflow/operations/PreTransactionalOperation.java
transaction-flow/src/main/java/uk/gov/pay/commons/transactionflow/operations/TransactionalOperation.java
transaction-flow/src/test/java/uk/gov/pay/commons/transactionflow/TransactionFlowTest.java

This module is framework for combining `@Transactional` and `@NonTransactional` operations in to a single cohesive unit

P-2672 module=transaction-flow adding transaction flow module

---

README.md
pom.xml
utils/pom.xml
utils/src/main/java/uk/gov/pay/commons/utils/xray/AwsXrayBundle.java
utils/src/main/java/uk/gov/pay/commons/utils/xray/XRayHttpClientFilter.java
utils/src/main/java/uk/gov/pay/commons/utils/xray/XRaySessionProfiler.java
utils/src/main/resources/sampling-rules.json

Common xray code for Pay's java microservices. Code was moved over from  https://github.com/alphagov/pay-adminusers/pull/211/files.
@oswaldquek

Pp 2495 common xray code

---

utils/src/main/java/uk/gov/pay/commons/utils/xray/XRayHttpClientFilter.java
utils/src/main/java/uk/gov/pay/commons/utils/xray/XRaySessionProfiler.java

Trying to begin a subsegment will throw an error if there is no current
segment.
@oswaldquek

PP-4082: Don't record subsegment if there is no current segment

---

model/src/main/java/uk/gov/pay/commons/model/SupportedLanguageJsonDeserializer.java
model/src/test/java/uk/gov/pay/commons/model/SupportedLanguageJsonDeserializerTest.java
pom.xml

- Added Deserializer for SupportedLanguage to be mapped directly from JSON to enum.
- Added unit tests
- Added Jackson 2.9.7 to pom.xml

PP-4304 Added JSON Deserializer for SupportedLanguage

---

testing/src/main/java/uk/gov/pay/commons/testing/db/PostgresDockerRule.java

This reverts commit aaa955ab91844d5805182a31888d95c6b69ac2f4.
This was a test, which didn't work and shouldn't have been included in my
previous PR.

Revert "BAU: Make PostgresDockerRule threadsafe"

---

model/src/main/java/uk/gov/pay/commons/api/resources/ResourceStrings.java

Makes the resource strings public instead of package private so they can be accessed by all services as required.
Author: @cobainc0

PP-4226 Make resource strings available to microservices

---

utils/src/main/java/uk/gov/pay/commons/utils/xray/XRayHttpClientFilter.java

Rather than check these variables for nullity 3 times, check them once before
we try to use them.
Found by lgtm.com

BAU: Check XRray subsegment before trying to use it

---

utils/pom.xml
utils/src/main/java/uk/gov/pay/commons/utils/logging/LoggingFilter.java
utils/src/test/java/uk/gov/pay/commons/utils/logging/LoggingFilterTest.java

This is a generic filter which logs the start and end of every request.

PP-4660: Import LoggingFilter from pay-publicauth

---

utils/src/main/java/uk/gov/pay/commons/utils/xray/XRaySessionProfiler.java

- Currently if the session is null, connector cannot connect to the database anymore
with @heathd

PP-4790 Protect XRaySessionProfiler from NPE

---

model/src/main/java/uk/gov/pay/commons/api/json/ExternalMetadataDeserialiser.java
model/src/test/java/uk/gov/pay/commons/api/json/ExternalMetadataDeserialiserTest.java

The ExternalMetadataDeserialiser needs to be used by publicapi too.

PP-4886: Make ExternalMetadataDeserialiser from connector common

---

model/src/main/java/uk/gov/pay/commons/api/json/ExternalMetadataSerialiser.java

Moving this from pay-connector as publicapi could use it too.

PP-4886: ExternalMetadataSerialiser is common code

---

model/src/main/java/uk/gov/pay/commons/model/ErrorIdentifier.java

Used for error responses created by Connector and Direct debit connector and for handling these in Public API

PP-5142 Add ErrorIdentifier enum

---

pom.xml
validation/pom.xml
validation/src/main/java/uk/gov/pay/commons/validation/DateTimeUtils.java
validation/src/main/java/uk/gov/pay/commons/validation/DateValidator.java
validation/src/main/java/uk/gov/pay/commons/validation/ValidDate.java
validation/src/test/java/uk/gov/pay/commons/validation/DateTimeUtilsTest.java

There is a need to do these validations in directdebit-connector too.

PP-5302: Move common date validations from publicapi

---

utils/src/main/java/uk/gov/pay/commons/utils/healthchecks/DatabaseHealthCheck.java
utils/src/main/java/uk/gov/pay/commons/utils/metrics/DatabaseMetricsService.java
utils/src/test/java/uk/gov/pay/commons/utils/metrics/DatabaseMetricsServiceTest.java

Import the healthcheck and metric-gathering code from [pay-publicauth](https://github.com/alphagov/pay-publicauth) into `utils`

REP-188: Add common database utility code

---

pom.xml
utils/src/main/java/uk/gov/pay/commons/utils/logging/LogstashConsoleAppenderFactory.java

- Adds the Logstash factory to pay-java-commons for usage across all our
applications.

PP-5511 Add Logstash Factory

---

logging/pom.xml
logging/src/main/java/uk/gov/pay/logging/LogstashConsoleAppenderFactory.java
pom.xml

- Move the logstash dependency to the new logging pom.xml submodule.

BAU Move Dependencies To Submodule

---

logging/src/main/java/uk/gov/pay/logging/LoggingKeys.java

Add `REFUND_EXTERNAL_ID` and `CHARGE_TOKEN_ID`.

PP-5761 Add Logging Keys

---

logging/pom.xml
logging/src/main/java/uk/gov/pay/logging/LoggingFilter.java
logging/src/main/java/uk/gov/pay/logging/LoggingKeys.java
logging/src/test/java/uk/gov/pay/logging/LoggingFilterTest.java
utils/pom.xml

I think logging classes should be in the logging submodule. Happy for this to be rejected if there are strong opinions about it though.

Pp 5761 logging refactor

---

logging/pom.xml
utils/pom.xml

- Upgrades dropwizard version to 2.0.0
- Add required library `org.glassfish.jersey.bundles.repackaged` for `com.google.common.base.Stopwatch`

PP-6001 upgrade dropwizard version 2.0.0

---

README.md

Updates the readme with a bintray provided badge to inform users of the current version, also provides a link to bintray

Update README with version badge

---

model/src/main/java/uk/gov/pay/commons/api/validation/MapKeyInsensitiveUnique.java
model/src/main/java/uk/gov/pay/commons/api/validation/MapKeyInsensitiveUniqueValidator.java
model/src/main/java/uk/gov/pay/commons/api/validation/ValidExternalMetadata.java
model/src/test/java/uk/gov/pay/commons/model/charge/ExternalMetadataTest.java

- validate metadata's keyset for case insensitive duplicates (key, Key)
with @alexbishop1

PP-6158 validate metadata for case insensitive duplicate keys

---

testing/src/main/java/uk/gov/pay/commons/testing/db/PostgresContainer.java

PP-6084 Upgrade test db to 11.1

---

model/src/main/java/uk/gov/pay/commons/api/json/MicrosecondPrecisionDateTimeDeserializer.java
model/src/main/java/uk/gov/pay/commons/api/json/MicrosecondPrecisionDateTimeSerializer.java
model/src/test/java/uk/gov/pay/commons/api/json/MicrosecondPrecisionDateTimeDeserializerTest.java
model/src/test/java/uk/gov/pay/commons/api/json/MicrosecondPrecisionDateTimeSerializerTest.java

These are used in both connector and ledger, adding here so these
projects don't need need to implement their own versions

PP-6472 Add DateTime serializers

---

testing/pom.xml
testing/src/main/java/uk/gov/pay/commons/testing/db/PostgresDockerExtension.java

- Added Postgres extension (to support JUnit5 integration tests) to start and stop database, and is similar to PostgresDockerRule

PP-6708 Postgres extension

---

pom.xml

It appears this is no longer needed

bau: Remove junit dependency

---

README.md

- Update the README to reflect the management of Maven Central via Github Actions

PP-7938 Update README

---

validation/src/main/java/uk/gov/service/payments/commons/validation/DateTimeUtils.java
validation/src/test/java/uk/gov/service/payments/commons/validation/DateTimeUtilsTest.java

These were detected by running [error prone](https://github.com/google/error-prone) against this repo.

bau: Errors detected by Error Prone

---

.github/workflows/build-and-publish.yml
.github/workflows/run-tests.yml

- add new actions to run unit tests on pull requests

PP-8082 add running unit tests to github actions

---

.github/workflows/build-and-publish.yml

- distribution is an invalid tag for release, remove it

PP-8082 fix main build

---

pom.xml
queue/pom.xml
queue/src/main/java/uk/gov/service/payments/commons/queue/exception/QueueException.java
queue/src/main/java/uk/gov/service/payments/commons/queue/model/QueueMessage.java
queue/src/main/java/uk/gov/service/payments/commons/queue/sqs/AbstractQueue.java
queue/src/main/java/uk/gov/service/payments/commons/queue/sqs/SqsQueueService.java
queue/src/test/java/uk/gov/service/payments/commons/queue/sqs/SqsQueueServiceTest.java

Add common classes for SQS queues that are used across different Java apps.

PP-9260 Add common SQS classes

---

logging/src/main/java/uk/gov/service/payments/logging/LoggingKeys.java

- add a new logging key for Stripe event

PP-9258 add new logging key

---

.github/workflows/build-and-publish.yml
.github/workflows/run-tests.yml

checked for Ubuntu 18.04 images and updated to ubuntu-latest.

PP-10035 Updated ubuntu 18.04 to ubuntu-latest

---

model/src/main/java/uk/gov/service/payments/commons/model/agreement/AgreementStatus.java

- add new `INACTIVE` status to `AgreementStatus`

PP-10949 add a new agreement status enum

---

logging-dropwizard-3/pom.xml
logging-dropwizard-3/src/main/java/uk/gov/service/payments/logging/GovUkPayDropwizardRequestJsonLogLayout.java
logging-dropwizard-3/src/main/java/uk/gov/service/payments/logging/GovUkPayDropwizardRequestJsonLogLayoutFactory.java
logging-dropwizard-3/src/main/java/uk/gov/service/payments/logging/LoggingFilter.java
logging-dropwizard-3/src/main/java/uk/gov/service/payments/logging/LoggingKeys.java
logging-dropwizard-3/src/main/java/uk/gov/service/payments/logging/LogstashConsoleAppenderFactory.java
logging-dropwizard-3/src/main/java/uk/gov/service/payments/logging/RestClientLoggingFilter.java
logging-dropwizard-3/src/test/java/uk/gov/service/payments/logging/GovUkPayDropwizardRequestJsonLogLayoutFactoryTest.java
logging-dropwizard-3/src/test/java/uk/gov/service/payments/logging/LoggingFilterTest.java
logging-dropwizard-3/src/test/java/uk/gov/service/payments/logging/RestClientLoggingFilterTest.java
pom.xml

- added logging module with support for `dropwizard 3.x`
- updated java commons parent pom to reference new module

BAU `dropwizard 3.x` logging support

---

utils/pom.xml
utils/src/main/java/uk/gov/service/payments/commons/utils/prometheus/EcsContainerMetadataVersion4.java
utils/src/main/java/uk/gov/service/payments/commons/utils/prometheus/PrometheusDefaultLabelSampleBuilder.java
utils/src/test/java/uk/gov/service/payments/commons/utils/prometheus/PrometheusDefaultLabelSampleBuilderTest.java

[It works!](https://gds.slack.com/archives/CNZFSNM0S/p1689859492329799)
PrometheusDefaultLabelSampleBuilder is meant to be used by all of our java apps.

PP-11223 prometheus default label

---

utils/src/main/java/uk/gov/service/payments/commons/utils/prometheus/PrometheusDefaultLabelSampleBuilder.java
utils/src/test/java/uk/gov/service/payments/commons/utils/prometheus/PrometheusDefaultLabelSampleBuilderTest.java

Fixes a bug where Dropwizard supplied metrics labels were being overwritten with ECS metadata.

PP-11226 ensure all labels are applied

---

logging-dropwizard-3/pom.xml
logging/pom.xml

Reverts alphagov/pay-java-commons#689

Revert "Bump logstash-logback-encoder from 7.3 to 7.4"

---

utils/pom.xml

- update eclipselink to latest
with @alexbishop1

P-11652 update eclipselink

---

pom.xml

Reverts alphagov/pay-java-commons#814

Revert "Bump org.apache.maven.plugins:maven-gpg-plugin from 3.2.1 to 3.2.2"

---

.github/dependabot.yml
logging-dropwizard-3/pom.xml
logging-dropwizard-3/src/main/java/uk/gov/service/payments/logging/LoggingFilter.java
model/pom.xml
model/src/main/java/uk/gov/service/payments/commons/api/json/MicrosecondPrecisionDateTimeSerializer.java
model/src/main/java/uk/gov/service/payments/commons/api/validation/ValidExternalMetadata.java
model/src/main/java/uk/gov/service/payments/commons/model/jsonpatch/JsonPatchRequest.java
model/src/test/java/uk/gov/service/payments/commons/model/SupportedLanguageJsonDeserializerTest.java
model/src/test/java/uk/gov/service/payments/commons/model/charge/ExternalMetadataTest.java
pom.xml
queue/pom.xml
testing/pom.xml
utils/pom.xml
validation/pom.xml

Upgrade project to use Dropwizard 3

PP-12177 move everything to dropwizard 3

---

.github/dependabot.yml

Fine tune dependabot config so it only opens one PR per update

PP-12177 fine tune dependabot config

---

.secrets.baseline
testing/pom.xml
testing/src/main/java/uk/gov/service/payments/commons/testing/db/PostgresContainer.java
testing/src/main/java/uk/gov/service/payments/commons/testing/db/PostgresTestHelper.java

Refactor to remove Spotify docker. Replace it with testcontainer.

PP-12177 implement despotifydockerification

---

.github/workflows/build-and-publish.yml

Uses the new Sonatype token and username.

PP-12831: Replace Maven publish action with setup-java

---

.github/workflows/build-and-publish.yml

Hardcode .m2 directory for the server settings

PP-12831 refine maven settings path

---

.github/workflows/build-and-publish.yml
logging-dropwizard-3/src/test/java/uk/gov/service/payments/logging/Fake.java

add --batch-mode to maven deploy commend
add a fake class (Fake) to trigger release (shall be removed later)

PP-12831 add batch mode to maven deploy

---

.github/workflows/build-and-publish.yml
logging-dropwizard-3/src/test/java/uk/gov/service/payments/logging/Fake.java

Reverts alphagov/pay-java-commons#902

Revert "PP-12831 add gpg signing"

---

.github/workflows/build-and-publish.yml
.github/workflows/run-tests.yml
pom.xml

- rename the mvn profile that is used for signing artefacts
- amend GHA workflow to call new profile
- reduce mvn output on CI

PP-12831 build and publish workflow

---

.github/workflows/build-and-publish.yml
.github/workflows/run-tests.yml
pom.xml
testing/pom.xml
testing/src/main/java/uk/gov/service/payments/commons/testing/pact/consumers/PayPactProviderRule.java
testing/src/test/java/uk/gov/service/payments/commons/testing/pact/consumers/PayPactProviderRuleTest.java
testing/src/test/java/uk/gov/service/payments/commons/testing/pact/consumers/PayPactPublishingTest.java

Upgrade build, tests, and release to Java 21
Change Java distribution to temurin (adopt stopped new releases at Java 16)
Refactor pact test to take advantage of newer version

PP-12789 upgrade to Java 21

---

logging-dropwizard-4/pom.xml
model-dropwizard-4/pom.xml

We don't want to upgrade to Dropwizard 5.x just yet

PP-14349 suppress Junit5 upgrade
