testing/pom.xml
Version 3.10.4 is very old, and when uk.gov.pay:testing was being included in
another project it was causing tests in that project to fail with
```
java.lang.IllegalStateException: org.xml.sax.SAXNotRecognizedException:
http://javax.xml.XMLConstants/feature/secure-processing
```
Upgrading mockserver versions solves the problem.
@oswald.quek
=> bau: Upgrade mockserver version

testing/src/main/java/uk/gov/pay/commons/testing/pact/consumers/MultiPacts.java, testing/src/main/java/uk/gov/pay/commons/testing/pact/consumers/PactProviderRule.java, testing/src/main/java/uk/gov/pay/commons/testing/pact/consumers/Pacts.java, testing/src/test/java/uk/gov/pay/commons/testing/pact/consumers/PactProviderRuleTest.java, testing/src/test/java/uk/gov/pay/commons/testing/pact/consumers/PactPublishingTest.java, testing/src/test/resources/pacts/consumer-order-service.json
PP-3845 is about checking pact compatibility, e.g. can I deploy service A to
staging given there is service B in staging as well. The issue is sometimes
consumer pact tests are written in development and by default are published to
the pact broker - at this stage no provider tests have been written. This
causes pact compatibility check to fail as the pact broker now has knowledge of
the new pact.
This commit gives the option to not publish a pact by deleting it from the
target/pacts directory, which the pact:publish maven plugin looks into to
publish pacts to the broker.
It would be nice to specify what pacts not to publish in the pact:publish
plugin, an issue has been raised here
https://github.com/DiUS/pact-jvm/issues/711.
@oswaldquek
=> PP-3845: Add ability to not publish pacts

utils/src/main/java/uk/gov/pay/commons/utils/xray/Xray.java
It turns out using Bundles does not work. I am not completely sure why but
looking at https://www.dropwizard.io/1.0.5/docs/manual/internals.html it is
possible this is either due to:
1. the Cli not being instantiated before the `bundle.initialize(bootstrap)` is
run
2. the environment is only created during the `cli.run` phase so the xray stuff
needs to be instantiated after the environment is created, not before when
`bundle.initialize(bootstrap)` is run during the `initialize(bootstrap)` phase.
With this commit, dropwizard apps simply need to call Xray.init in the
Application's run method.
@oswaldquek
=> PP-2495: Initialize AWS Xray within a static method

model/pom.xml, model/src/main/java/uk/gov/pay/commons/model/SupportedLanguage.java, model/src/main/java/uk/gov/pay/commons/model/SupportedLanguageJpaConverter.java, model/src/test/java/uk/gov/pay/commons/model/SupportedLanguageTest.java, pom.xml
Add a new Maven submodule called `model` and add a copy of the `SupportedLanguage` enum in it, so it can be shared across multiple Java projects.
with @DanailMinchev
=> PP-4095 Add new model Maven module with SupportedLanguage enum

Jenkinsfile
Using the jenkins build number will fail when jenkins is reset and the build
numbers are reset to 1.
@oswaldquek
=> bau: use git commit for version

utils/pom.xml, utils/src/main/java/uk/gov/pay/commons/utils/xray/XRayHttpClientFilter.java
Also switch to just depending on `org.eclipse.persistence.jpa` rather than the full EclipseLink because we only use the JPA functionality.
Set the Maven dependency scope to `compile`, in line with the EclipseLink documentation.
See https://wiki.eclipse.org/EclipseLink/Maven for details.
Remove an unused EclipseLink import in `XRayHttpClientFilter`.
=> PP-4248 In utils module, upgrade EclipseLink from 2.6.4 to 2.7.3

model/src/main/java/uk/gov/pay/commons/api/resources/ResourceStrings.java, model/src/main/java/uk/gov/pay/commons/model/TokenPaymentType.java, model/src/main/java/uk/gov/pay/commons/model/directdebit/agreement/AgreementType.java, model/src/main/java/uk/gov/pay/commons/model/directdebit/agreement/MandateType.java, model/src/test/java/uk/gov/pay/commons/model/TokenPaymentTypeTest.java
adds Enums
- TokenPaymentType & unit test,
- AgreementType, 
- MandateType
- new class ResourceStrings for reuse in place of hardcoded strings in Resources
We want Types to be moved here for consistency, remove duplication of code and tests and allow sharing between common Types. We also want to replace hardcoded Strings in PublicApi. 
e.g TokenPaymentType is used in both PublicApi and PublicAuth. Once we have this we will update the version used in those microservices and remove the Types from them.
Author: @cobainc0
=> PP-4226 Share TokenPaymentType across all microservices

testing/pom.xml, testing/src/main/java/uk/gov/pay/commons/testing/db/PostgresContainer.java, testing/src/main/java/uk/gov/pay/commons/testing/db/PostgresDockerRule.java
We have copies of this code in all our projects for bringing up and tearing
down a postgres container in order to run tests. Bring it into our central
testing library and then share it back out.
See https://github.com/alphagov/pay-adminusers/pull/290 for an example of what this replaces and how it would be used
=> PP-4474: Import postgres container handling code from adminusers

testing/pom.xml
Just importing the javax.json API is not enough - we also need an
implmentation.
=> BAU: Add a JSON parser implementation

model/pom.xml, pom.xml, testing/pom.xml
Move the Jackson dependencies out of the top-level POM and put them in the model module POM (which is where they are needed) so that users of other modules don’t get them unnecessarily.
Upgrade the Jackson dependency in the testing module from 2.9.5 to 2.9.7 and make all Jackson dependencies use the `${jackson.version}` property.
=> BAU: Move Jackson from top POM to model and use 2.9.7 everywhere

pom.xml
For some reason we didn't pin this plugin to a version like we do with all our
others.
=> PP-4573: Add a version constraint to maven-source-plugin

Jenkinsfile
Change the version numbering scheme from being like 1.0.0-a4ac0cce47da65f86c580f856f60f98a62e88ee9 (where a4ac0cce47da65f86c580f856f60f98a62e88ee9 is the Git SHA of the commit) to being like 20190108160351 where 20190108160351 is a timestamp in the form yyyyMMddHHmmss.
This makes it easy to compare version numbers to see which is newer and also means that newer versions sort lexicographically after older versions.
=> Change version number scheme to be timestamp rather than Git SHA

model/src/main/java/uk/gov/pay/commons/model/ApiResponseDateTimeFormatter.java, model/src/test/java/uk/gov/pay/commons/model/ApiResponseDateTimeFormatterTest.java
We use `DateTimeFormatter.ISO_INSTANT.withZone(UTC)` to format a lot of the timestamps we put in API responses, which produces strings like `"2015-10-21T07:28:00.123Z"`. The fractional part, if present, will have either three, six or nine digits, depending on the precision available.
When one asks Java 8 for the current time, it always returns the time with millisecond precision, even if the underlying system clock can do better. Java 9 and above don’t have this limitation
and will return higher accuracy if the system clock offers it (see https://bugs.openjdk.java.net/browse/JDK-8068730 for details). On Linux and macOS, this usually means microsecond precision.
Therefore, when `DateTimeFormatter.ISO_INSTANT.withZone(UTC)` is used to format the current time on Java 8, the resulting string …
=> PP-4595 ISO instant date/time formatter with millisecond precision

Jenkinsfile
Change the version number scheme from being like 20190115100435 to being like 1.0.20190115100435 because it’s more in line with Maven conventions and will hopefully make Dependabot less confused about what the latest version is.
=> BAU: Change version number scheme to be more Mavenesque

utils/pom.xml, utils/src/main/java/uk/gov/pay/commons/utils/startup/ApplicationStartupDependentResource.java, utils/src/main/java/uk/gov/pay/commons/utils/startup/ApplicationStartupDependentResourceChecker.java, utils/src/main/java/uk/gov/pay/commons/utils/startup/DatabaseStartupResource.java, utils/src/test/java/uk/gov/pay/commons/utils/startup/ApplicationStartupApplicationStartupDependentResourceCheckerTest.java
Code imported from `pay-publicauth`.
This code is duplicated in all our Java microservices with databases. It allows
the apps to pause startup until their databases become available.
Example usage:
new ApplicationStartupDependentResourceChecker(new DatabaseStartupResource(conf.getDataSourceFactory()), duration -> {
try { Thread.sleep(duration.getNano() / 1000); } catch (InterruptedException ignored) { }
}).checkAndWaitForResource();
=> PP-4616: Add support for waiting for database availability on startup

utils/src/main/java/uk/gov/pay/commons/utils/startup/ApplicationStartupDependentResourceChecker.java
If we want apps to use this class, having it package-private isn't going to help.
=> PP-4616: Make ApplicationStartupDependentResourceChecker public

utils/src/main/java/uk/gov/pay/commons/utils/startup/DatabaseStartupResource.java
If we want people to use this, it helps if they can access it.
=> PP-4616: Make DatabaseStartupResource constructor public

utils/src/main/java/uk/gov/pay/commons/utils/startup/ApplicationStartupDependentResourceChecker.java, utils/src/test/java/uk/gov/pay/commons/utils/startup/ApplicationStartupApplicationStartupDependentResourceCheckerTest.java
It's only the tests which need to pass in a custom 'waiter' to this class, so
provide a constructor that supplies a sensible default implementation for the
real consumers to use, making their lives easier.
=> PP-4616: Add a convenience constructor to ApplicationStartupDependentResourceChecker

utils/pom.xml, utils/src/main/java/uk/gov/pay/commons/utils/logging/LoggingFilter.java, utils/src/test/java/uk/gov/pay/commons/utils/logging/LoggingFilterTest.java
- Stop making up a placeholder request ID for requests which have none. If you want to log something in place of a missing value, make use of the fallback default behaviour of the `%X` log format placeholder when formatting log messages, i.e. `%X{Request-Id:-(none)}`
- Add optional support for recording response timing histograms using `dropwizard-metrics` (taken from `pay-cardid`'s `LoggingFilter`
=> PP-4606: Log request IDs more accurately; add response timing metrics

model/src/main/java/uk/gov/pay/commons/api/json/ApiResponseDateTimeSerializer.java, model/src/test/java/uk/gov/pay/commons/api/json/ApiResponseDateTimeSerializerTest.java
- To keep our ZDT external representation consistent, we created a serializer
that will format ZDT with millisecond precision. This will ease the
transition to Java 11
=> PP-4597 Added JSON serializer for ZonedDateTime

model/src/main/java/uk/gov/pay/commons/api/json/ApiResponseDateTimeDeserializer.java, model/src/main/java/uk/gov/pay/commons/model/ApiResponseDateTimeFormatter.java, model/src/test/java/uk/gov/pay/commons/api/json/ApiResponseDateTimeDeserializerTest.java
- To keep our ZDT internal representation consistent, we created a deserializer
that will parse String into ZonedDateTime. This will make our apps consistent
=> PP-4597 Added JSON deserializer for ZonedDateTime

utils/pom.xml, utils/src/main/java/uk/gov/pay/commons/utils/xray/XRaySessionProfiler.java, utils/src/test/java/uk/gov/pay/commons/utils/xray/XRaySessionProfilerTest.java
- Most of the metadata can be accessed independent of a connected session.
This is done using the DatabaseLogin object. This metadata can be skipped if
not available so we will populate only what we can find.
- We decided to avoid querying if the connection is null, as we observed that
after a database error, all subsequent calls to the profiler were using a
`disconnected` database session. We don't need to use a connection, no matter
what the status, so we will not use it at all.
- Added DropWizard testing to write a small unit test to check that the
properties are set
=> PP-4790 Get metadata from database login

testing/src/main/java/uk/gov/pay/commons/testing/db/PostgresContainer.java
This isn't yet available in AWS, but we can start testing against it.
=> PP-4832: Upgrade postgresql to 9.6.12

model/src/main/java/uk/gov/pay/commons/model/DateTimeFormatters.java, model/src/test/java/uk/gov/pay/commons/model/DateTimeFormattersTest.java
This formatter can be used to ensure dates are formatted consistently to
millisecond precision, for example when creating expected string values for tests.
Whilst preparing Direct Debit Connector for Java 11 it is necessary to format the expected date string for tests to millisecond precision (currently using `DateTimeFormatter.ISO_INSTANT` which uses the level of precision offered by the system, on my local machine this is to nanoseconds). In anticipation that this will be useful in other projects I've added it here to pay-commons.
=> PP-4951 Add a Millisecond ISO Instant formatter for common use.

model/pom.xml, model/src/main/java/uk/gov/pay/commons/api/validation/ExternalJsonMetadataValidator.java, model/src/main/java/uk/gov/pay/commons/api/validation/ValidExternalJsonMetadata.java, model/src/test/java/uk/gov/pay/commons/api/Validation/ValidExternalJsonMetadataTest.java, pom.xml, utils/pom.xml
Add `ValidExternalJsonMetadata` annotation and associated validator.
Add unit tests for validation.
=> PP-4884 Add annotation and validation for external metadata as JsonNode.

model/src/main/java/uk/gov/pay/commons/api/json/ExternalMetadataDeserialiser.java, model/src/test/java/uk/gov/pay/commons/api/json/ExternalMetadataDeserialiserTest.java
- Check that metadata is an object before trying to convert to a map. Throw a
`JsonMappingException` with a useful error if not.
=> PP-4884 Check that metadata is an object

model/src/main/java/uk/gov/pay/commons/api/json/ExternalMetadataDeserialiser.java, model/src/test/java/uk/gov/pay/commons/api/json/ExternalMetadataDeserialiserTest.java
It's been agreed with @danworth and @alexbishop1 we should be lenient and
accept create payment requets where metadata is empty:
```
"metadata": {}
```
If this happens we want to treat the payment as if it had no metadata.
Therefore this needs to be serialized to null which means the payment will have
no jsonb metadata in the database which is what we want.
=> PP-4886: Serialise empty metadata string to null object

testing/pom.xml, testing/src/main/java/uk/gov/pay/commons/testing/pact/consumers/PactProviderRule.java, testing/src/main/java/uk/gov/pay/commons/testing/port/PortFactory.java
- Remove dependency on mockserver
- Move PortFactory from pay-connector's project so it can be used by publicapi
as well
=> PP-4911: Deprecate mockserver

testing/pom.xml, testing/src/main/java/uk/gov/pay/commons/testing/matchers/HamcrestMatchers.java
Moving the following code (from https://github.com/alphagov/pay-direct-debit-connector/blob/master/src/test/java/uk/gov/pay/directdebit/mandate/resources/MandateResourceIT.java#L176-L178):
```
private Matcher<Object> optionalDescriptionMatcher(String description) {
return description == null ? is(nullValue()) : is(notNullValue());
}
```
as it can be used in other projects.
=> PP-5297: Optional matcher

model/src/main/java/uk/gov/pay/commons/model/WrappedStringValue.java, model/src/test/java/uk/gov/pay/commons/model/WrappedStringValueTest.java
Add an abstract class that wraps a string. This can make the implementation of our burgeoning collection of specific value types (types that represent particular IDs etc.) simpler because they don’t each need to implement `equals(…)` and the like (which can be surprisingly hard to get right sometimes!).
The wrapped string must not be null. To be considered equal, two objects must have both the same runtime type and the same string value: instances of different subtypes that wrap the same string are not equal.
Use it like this:
```java
public class ExternalPaymentId extends WrappedStringValue {
private ExternalPaymentId(String id) {
super(id);
}
public static ExternalPaymentId valueOf(String id) {
return new ExternalPaymentId(id);
}
}
```
=> PP-5318 Abstract type for value types that wrap strings

logging/pom.xml, logging/src/main/java/uk/gov/pay/logging/LoggingKeys.java, pom.xml
An interface of string constants to be used as structured logging keys in an attempt to encourage consistency.
Generally, key names are quite broad, for example `provider_id`, which could be a provider’s ID for a payment, mandate, refund etc. However, the data recorded could compose multiple keys to aid
disambiguation. For instance, one could have a log line with properties like this:
```json
{
"provider_id": "foo",
"provider": "sandbox",
"payment_type": "card",
"resource_type": "payment"
}
```
Here, it’s clear that the `provider_id` refers to a sandbox card payment. Someone searching the logs who has a provider ID but doesn’t know what it refers to could just search for the `provider_id`, while someone who knows they want log lines related to a sandbox card payment could add the extra …
=> PP-5542 Initial structured logging keys for Java applications

logging/src/main/java/uk/gov/pay/logging/LoggingKeys.java
Add some Javadoc to `LoggingKeys` noting that it must be kept in sync with the equivalent Node.js files.
=> PP-5542 Reference Node.js logging keys in Java logging keys

testing/src/main/java/uk/gov/pay/commons/testing/pact/provider/CreateTestSuite.java
This pulls https://github.com/alphagov/pay-connector/blob/master/src/test/java/uk/gov/pay/connector/pact/ContractTestSuite.java#L25-L40 into a common utility for other provider tests to use.
=> PP-5670: Utility class for creating a TestSuite

logging/pom.xml, logging/src/main/java/uk/gov/pay/logging/LogstashConsoleAppenderFactory.java
We want our java applications to log its service name in the json logs. We
don't want to have to do this by adding the name in the MDC; its easier to be
able to define it in the application's config yaml file. Unfortunately due to
our custom LogstashConsoleAppenderFactory - which nicely logs structured
arguments and various GDS standard keys (E.g. '@timestamp', '@version') - we don't
use the standard dropwizard json logging which would have allowed us to use the
`additionalFields` in the config yaml file (see
`io.dropwizard.logging.json.layout.EventJsonLayout`). This commit allows our
java apps to have this sort of config:
```
logging:
level: ERROR
appenders:
- type: logstash-console
threshold: ALL
timeZone: UTC
target: stdout
customFields:
label: "directdebit-connector"
layout:
type: …
```
=> PP-5735: Allow json logging of static data

utils/src/main/java/uk/gov/pay/commons/utils/logging/LoggingFilter.java, utils/src/test/java/uk/gov/pay/commons/utils/logging/LoggingFilterTest.java
The http `X-Request-Id` header is put in an MDC which will become a key in an application's json log output.
=> PP-5735: Use GDS convention for json logging key names

logging/pom.xml, logging/src/main/java/uk/gov/pay/logging/GovUkPayAccessJsonLayoutFactory.java, logging/src/main/java/uk/gov/pay/logging/GovUkPayDropwizardRequestJsonLogLayoutFactory.java, logging/src/test/java/uk/gov/pay/logging/GovUkPayDropwizardRequestJsonLogLayoutFactoryTest.java
Common class that configures dropwizard request logs, so projects can configure
```
server:
requestLog:
appenders:
- type: console
layout:
type: govuk-pay-access-json
additionalFields:
container: "connector" #for example
```
instead of the current
```
server:
requestLog:
appenders:
- type: console
layout:
type: access-json
timestampFormat: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
customFieldNames:
timestamp: "@timestamp"
userAgent: "user_agent"
requestTime: "response_time"
uri: "url"
protocol: "http_version"
status: "status_code"
contentLength: "content_length"
remoteAddress: "remote_address"
additionalFields:
container: "connector"
"@version": 1
```
=> PP-5776: Custom json logging factory

logging/src/main/java/uk/gov/pay/logging/LoggingKeys.java
There are now `PAYMENT_EXTERNAL_ID` and `REFUND_EXTERNAL_ID` keys in
LoggingKeys. This is pertinent to a request like
`/v1/api/accounts/{accountId}/charges/{chargeId}/refunds/{refundId}` in
connector which will log the external charge id and external refund id in the
same json log. The current EXTERNAL_ID is only used once in
pay-direct-debit-connector to log the mandate id and so it's better named as
MANDATE_EXTERNAL_ID.
=> PP-5893: Specify the type of external id

model/src/main/java/uk/gov/pay/commons/model/Source.java
- Adds the source enum to pay-java-commons so all our apps can access it
=> PP-6012 Add Source To pay-java-commons

model/src/main/java/uk/gov/pay/commons/model/WrappedStringValue.java, model/src/test/java/uk/gov/pay/commons/model/WrappedStringValueTest.java
- Use `var` rather than explicit type in one place
- Use Hamcrest `assertThat` rather than JUnit’s deprecated `assertThat`
- Remove an unnecessary `@SuppressWarnings` element
=> BAU — Tweak WrappedStringValue and its test

logging/src/main/java/uk/gov/pay/logging/LoggingKeys.java
Add gateway_payout_id and stripe_connect_account_id logging keys to be
used for log lines about payouts.
=> PP-6565 Add logging keys for payouts

logging/pom.xml, logging/src/test/java/uk/gov/pay/logging/GovUkPayDropwizardRequestJsonLogLayoutFactoryTest.java, logging/src/test/java/uk/gov/pay/logging/LoggingFilterTest.java, model/src/test/java/uk/gov/pay/commons/api/json/ApiResponseDateTimeDeserializerTest.java, model/src/test/java/uk/gov/pay/commons/api/json/ApiResponseDateTimeSerializerTest.java, model/src/test/java/uk/gov/pay/commons/api/json/ExternalMetadataDeserialiserTest.java, model/src/test/java/uk/gov/pay/commons/api/json/MicrosecondPrecisionDateTimeDeserializerTest.java, model/src/test/java/uk/gov/pay/commons/api/json/MicrosecondPrecisionDateTimeSerializerTest.java, model/src/test/java/uk/gov/pay/commons/model/ApiResponseDateTimeFormatterTest.java, model/src/test/java/uk/gov/pay/commons/model/SupportedLanguageJsonDeserializerTest.java, model/src/test/java/uk/gov/pay/commons/model/SupportedLanguageTest.java, model/src/test/java/uk/gov/pay/commons/model/TokenPaymentTypeTest.java, model/src/test/java/uk/gov/pay/commons/model/WrappedStringValueTest.java, model/src/test/java/uk/gov/pay/commons/model/charge/ExternalMetadataTest.java, pom.xml, testing/pom.xml, testing/src/main/java/uk/gov/pay/commons/testing/db/PostgresContainer.java, testing/src/main/java/uk/gov/pay/commons/testing/db/PostgresDockerRule.java, utils/pom.xml, utils/src/test/java/uk/gov/pay/commons/utils/metrics/DatabaseMetricsServiceTest.java, utils/src/test/java/uk/gov/pay/commons/utils/startup/ApplicationStartupApplicationStartupDependentResourceCheckerTest.java, utils/src/test/java/uk/gov/pay/commons/utils/xray/XRaySessionProfilerTest.java, validation/src/test/java/uk/gov/pay/commons/validation/DateTimeUtilsTest.java
- Upgrades all modules (except testing) to Junit5.
- Most of tests (expect pact provider & consumer tests) now use Junit5 api for tests and assertions. Pact tests uses @\Rule annotations which will need to be replaced by extensions and to be looked into separately.
- Uses surefire plugin to run tests (both vintage - junit4 tests & jupiter - junit5 tests). Without the plugin, it is possible that tests won't run if Maven version is not the latest on target platform.
=> PP-6708 Upgrade to Junit5

.secrets.baseline, model/src/main/java/uk/gov/pay/commons/api/validation/ValidExternalMetadata.java, model/src/main/java/uk/gov/pay/commons/model/charge/ExternalMetadata.java, model/src/test/java/uk/gov/pay/commons/model/charge/ExternalMetadataTest.java
Increase the maximum number of characters allowed for a metadata value associated with a payment from 50 characters to 100.
Introduce some constants to make it easier to reuse maximum and minimum sizes relating to metadata elsewhere.
=> PP-7067 Increase maximum metadata value length from 50 to 100

validation/src/main/java/uk/gov/pay/commons/validation/DateTimeUtils.java, validation/src/test/java/uk/gov/pay/commons/validation/DateTimeUtilsTest.java
- add a validation option for non-zoned string representation of a date, like 2020-09-19
- add relevant test
=> PP-7211 add non zoned date only string validator

model/src/main/java/uk/gov/pay/commons/jpa/CardExpiryDateConverter.java, model/src/main/java/uk/gov/pay/commons/model/CardExpiryDate.java, model/src/test/java/uk/gov/pay/commons/jpa/CardExpiryDateConverterTest.java, model/src/test/java/uk/gov/pay/commons/model/CardExpiryDateTest.java
Introduce a `CardExpiryDate` type to model card expiry dates. This is essentially a wrapper around a 2-digit month and a 2-digit year, which are the hard-working aspects of a card expiry date.
The type can be constructed from a string in MM/yy format and has a `toString()` method that converts it back to this format.
In addition, it has convenience methods to get the month as ac2-digit string and the year as a 2-digit string or a 4-digitcstring (for the latter, the 2-digit string is prefixed with "20", ingraining but also centralising and encapsulating the assumption that already pervades our system).
The type also offers a method to produce to an equivalent `YearMonth` (again, assuming the year begins with "20").
As a bonus, the type exposes a regex pattern that can be used to validate a …
=> PP-7242 Introduce a CardExpiryDate type for, er, card expiry dates

model/src/main/java/uk/gov/pay/commons/model/CardExpiryDate.java, model/src/test/java/uk/gov/pay/commons/model/CardExpiryDateTest.java
In `CardExpiryDate`, rename some getters:
- `get2DigitMonth()` → `getTwoDigitMonth()`
- `get2DigitYear()` → `getTwoDigitYear()`
- `get4DigitYear()` → `getFourDigitYear()`
We are going to use these methods a lot in Freemarker templates. If you have an object `foo` that has a method `getWhatever()`, Freemarker lets you do the Java Beans-esque `${foo.whatever}` but this does not work if the first character after `get` in the method name is a digit.
This will really annoy me and it’s easy to fix earlier on so this is me doing that.
=> PP-7242 Rename some CardExpiryDate getters

model/src/main/java/uk/gov/pay/commons/model/CardExpiryDate.java, model/src/test/java/uk/gov/pay/commons/model/CardExpiryDateTest.java
A stray bracket in the card expiry date regex meant it would accept strings like `"10/(2"`.
=> PP-7242 Remove stray bracket from CardExpiryDate regex

logging/src/main/java/uk/gov/pay/logging/GovUkPayDropwizardRequestJsonLogLayoutFactory.java, logging/src/main/java/uk/gov/pay/logging/LoggingKeys.java
Modify the HTTP_STATUS logging key to be "status_code" as this is what
we use for request logging provided by dropwizard, and is also what we
use in our Node apps.
Have confirmed that we don't use this key anywhere in our applications
currently by doing a search in alphagov in github.
Add additional keys for "url", "method" and "response_time" so these can
be used in logging for requests that we do in addition to the dropwizard
logging. These other log lines contain additional information such as
resource ids involved in the request. Modify the dropwizard logging
template to use these keys to ensure we are consistent.
=> PP-7205 Add/modify logging keys for request logging

logging/src/main/java/uk/gov/pay/logging/RestClientLoggingFilter.java, logging/src/test/java/uk/gov/pay/logging/RestClientLoggingFilterTest.java
Currently this class is duplicated in publicapi, connector and products.
This can be safely moved to pay-java-commons as the request id that it
extracts from the MDC is set by LoggingFilter which is already in
pay-java-commons.
=> PP-7205 Move RestClientLoggingFilter to commons

logging/src/main/java/uk/gov/pay/logging/RestClientLoggingFilter.java
Log the status code as a structured argument when we receive a response
to a HTTP request we made.
Additionally, include the url, method and response_time as structured
arguments.
=> PP-7205 Log status codes for client responses

logging/src/main/java/uk/gov/pay/logging/GovUkPayDropwizardRequestJsonLogLayout.java, logging/src/main/java/uk/gov/pay/logging/GovUkPayDropwizardRequestJsonLogLayoutFactory.java
Make our implementation of the dropwizard AccessJsonLayoutBaseFactory even more custom by using our own implementation of AbstractJsonLayout to build the log line for the request.
This is required so that we can read the "X-Request-Id" header and log it as a key in the root object. If we used the dropwizard AccessJsonLayout class, it is only possibly to log this as a field in a "headers" object.
=> PP-7205 Log request id for dropwizard request logs

logging/src/main/java/uk/gov/pay/logging/GovUkPayDropwizardRequestJsonLogLayout.java, logging/src/main/java/uk/gov/pay/logging/LoggingKeys.java
We were logging the `remote_address` for all Dropwizard requests, but this was logging the address of the NGINX proxy.
NGINX adds an "X-Forwarded-For" header with the original IP address that we should log instead.
Add a logging key for "remote_address", as we also want to log using this key in public api when an invalid API key is used.
=> PP-7104 Log the forwarded for IP address

model/src/main/java/uk/gov/pay/commons/model/ApiResponseDateTimeFormatter.java, model/src/test/java/uk/gov/pay/commons/model/ApiResponseDateTimeFormatterTest.java
Update Javadoc for `ApiResponseDateTimeFormatter` to clarify it’s not just for `ZonedDateTime`s, moving the Javadoc to the `DateTimeFormatter` field rather than its containing class.
Add some tests to demonstrate that `ApiResponseDateTimeFormatter` works for Instants.
Do not set a time zone on the `DateTimeFormatterBuilder` because it’s never actually used (appending an ISO instant to a `DateTimeFormatterBuilder` always adds it using UTC). This does not change how dates and times are formatted.
=> PP-7590 Tweak ApiResponseDateTimeFormatter for Instants

model/src/main/java/uk/gov/pay/commons/api/json/ApiResponseInstantSerializer.java, model/src/test/java/uk/gov/pay/commons/api/json/ApiResponseInstantSerializerTest.java
`ApiResponseInstantSerializer` is to `Instant`s what `ApiResponseDateTimeSerializer` is to `ZonedDateTime`s.
=> PP-7590 Add JSON serialiser for Instants

model/src/main/java/uk/gov/pay/commons/jpa/InstantToUtcTimestampWithoutTimeZoneConverter.java, model/src/test/java/uk/gov/pay/commons/jpa/InstantToUtcTimestampWithoutTimeZoneConverterTest.java
Add a JPA `AttributeConverter` that converts between an `Instant` entity attribute and a `LocalDateTime` (assumed to be in UTC) for storing in a database column and vice versa.
Per JDBC 4.2, `LocalDateTime` maps to database columns of the type `TIMESTAMP WITHOUT TIME ZONE`.
This class is intended to be a replacement for `UTCDateTimeConverter` (found in connector and other services) except that it works with `Instant`s rather than `ZonedDateTime`s.
Contrary to its name, `UTCDateTimeConverter`’s actually stores dates and times in the database using the default time zone.
The input `ZonedDateTime` gets converted to a `Timestamp`, which is effectively just a count of nanoseconds since the epoch. The database driver then has to store this `Timestamp` in a `TIMESTAMP WITHOUT TIME ZONE` database …
=> PP-7590 JPA converter to convert between Instant and LocalDateTime

model/src/main/java/uk/gov/pay/commons/model/Source.java
Add `CARD_AGENT_INITIATED_MOTO` to the `Source` enum to join its friends `CARD_API`, `CARD_PAYMENT_LINK` and `CARD_EXTERNAL_TELEPHONE`.
`CARD_AGENT_INITIATED_MOTO` means the payment was created from an `AGENT_INITIATED_MOTO` product.
=> PP-7696 Add CARD_AGENT_INITIATED_MOTO to Source enum

.github/workflows/build-and-publish.yml, pom.xml, validation/src/main/java/uk/gov/service/payments/commons/validation/DateTimeUtils.java
Release pay-java-commons. Example of a successful release [here](https://www.bbc.co.uk/weather/2643743). This release follows the current convention we have, which is `1.0.yyyyMMddHHMMSS`.
See https://repo1.maven.org/maven2/uk/gov/service/payments/ for successfully released versions!
We should be able to search for our packages in https://search.maven.org/search?q=g:uk.gov.service.payments before merging this PR.
We will tackle removing bintray related stuff in another PR.
=> Pp 7938 release to maven

model/src/main/java/uk/gov/service/payments/commons/api/validation/JsonPatchRequestValidator.java, model/src/main/java/uk/gov/service/payments/commons/api/validation/RequestValidator.java, model/src/test/java/uk/gov/service/payments/commons/api/validation/JsonPatchRequestValidatorTest.java
Previously we were enforcing that a json patch value can not be an empty value. This is overly restrictive, as empty string is a valid value for an add or replace operation.
Note: this is a change in behaviour for existing library users. However, I believe the risk of regressions is low, as a per-field additional validation is required in which clients are likely to set any explicit requirements for the field.
=> PP-8496: remove emptiness check for json patch value attribute

pom.xml
Breaking publishing
Reverts alphagov/pay-java-commons#400
=> Revert "Bump nexus-staging-maven-plugin from 1.6.8 to 1.6.10"

logging/src/main/java/uk/gov/service/payments/logging/LoggingKeys.java
- Add gateway_dispute_id keys which is to be used for log lines about disputes.
=> PP-6565 Add logging key for disputes

model/src/main/java/uk/gov/service/payments/commons/model/AuthorisationMode.java
Enum will be used for specifying how payments will be authorised.
Current values are:
- "web": authorised by the user being directed to the `next_url` and filling out their payment details on the web page
- "moto_api": authorised by sending the card details directly for a MOTO payment using the new authorisation API
- "external": applies to payments that were added to Pay using the telephone payment notification API. These payments were authorised before details about them were sent to Pay.
=> PP-9142 Add AuthorisationMode enum

.github/workflows/build-and-publish.yml
See ADR: https://github.com/alphagov/pay-architecture/pull/49/files
This means that for PRs where the only changes are files in the `.github` folder, merging will not trigger the post-merge workflow (release and tag) or subsequent Concourse builds.
=> BAU: Exclude Github Actions/Dependabot from post-merge workflow

model/src/main/java/uk/gov/service/payments/commons/api/json/ApiResponseDateTimeSerializer.java, model/src/main/java/uk/gov/service/payments/commons/api/json/ApiResponseInstantWithMicrosecondPrecisionSerializer.java, model/src/main/java/uk/gov/service/payments/commons/api/json/MicrosecondPrecisionDateTimeSerializer.java, model/src/main/java/uk/gov/service/payments/commons/model/ApiResponseDateTimeFormatter.java, model/src/test/java/uk/gov/service/payments/commons/api/json/ApiResponseInstantWithMicrosecondPrecisionSerializerTest.java, model/src/test/java/uk/gov/service/payments/commons/model/ApiResponseDateTimeFormatterTest.java
Add `ApiResponseInstantWithMicrosecondPrecisionSerializer`, which is like `ApiResponseInstantSerializer` except that it uses microsecond precision rather than millisecond precision. It’s basically an equivalent of `MicrosecondPrecisionDateTimeSerializer` but for `Instant`s rather than `ZonedDateTime`s.
Also add `ISO_LOCAL_DATE_IN_UTC` to `ApiResponseDateTimeFormatter`, which is a direct copy of the same formatter in connector (and will eventually replace it).
Remove some `@JsonNaming` annotations from the serialisers because they’re not doing anything and we have equivalent annotations on the JSON classes themselves.
=> PP-10173 Add ApiResponseInstantWithMicrosecondPrecisionSerializer

testing/pom.xml, testing/src/main/java/uk/gov/service/payments/commons/testing/db/PostgresContainer.java, testing/src/main/java/uk/gov/service/payments/commons/testing/db/PostgresDockerExtension.java, testing/src/main/java/uk/gov/service/payments/commons/testing/db/PostgresDockerRule.java, testing/src/main/java/uk/gov/service/payments/commons/testing/db/PostgresTestHelper.java
- package `jnr-ffi` dependency, this dependency enables access to native libraries outside of the JVM (in this case, the docker client on ARM64)
- added abstract helper class to DRY up the Postgres JUnit testing rules/extensions
- overloaded the PostgresContainer constructor to allow user specified image tag
=> PP-10004 common testing harness ARM64 support

.github/workflows/run-tests.yml, .pre-commit-config.yaml, .secrets.baseline
**WHAT**
•	added a new github action to run detect-secrets
•	updated the pre-commit config to update the detect-secrets hook to version 1.4
•	rebaselined the repository's secrets baseline
Based on [alphagov/pay-webhooks#510](https://github.com/alphagov/pay-webhooks/pull/510)
**For reviewers**
•	ensure your local version of detect-secrets matches the latest version in use on this branch
•	run detect-secrets scan and ensure output matches the latest .secrets.baseline, the only change should be the generated timestamp
=> PP-10116: Add detect-secrets workflow and update version-v2

queue/src/main/java/uk/gov/service/payments/commons/queue/sqs/AbstractQueue.java, queue/src/main/java/uk/gov/service/payments/commons/queue/sqs/SqsQueueService.java, queue/src/test/java/uk/gov/service/payments/commons/queue/sqs/SqsQueueServiceTest.java
- Context: Occasional delays in database transations are causing an error whereby connector's task queue message handler picks up a new task before the associated database record has been updated
- Provided a method to add messages with a delivery delay, to allow sufficient time for the database to be updated before the message is handled
- Adjusted the associated unit test accordingly.
=> PP-10487 Allow delayed delivery of SQS messages

.github/workflows/_check_gpg_signing_key.yml
We aren't actively trusting the key, but the purpose of this test is only to check for expiry so changing the test to test for expiry _only_
I had the expiry check run in the unit tests workflow to test it now shows the key as not expired and you can see that successful run here: https://github.com/alphagov/pay-java-commons/actions/runs/4795620565/jobs/8530410304?pr=648
I made a simple docker file which use a repo that allows me to fake the time to test this:
```
$ cat Dockerfile
FROM alpine:3.17
RUN apk add --no-cache --update \
build-base \
git \
gnupg \
vim
RUN git clone https://github.com/wolfcw/libfaketime.git
WORKDIR /libfaketime/src
RUN make install
WORKDIR /
COPY foo.key /foo.key
ENV LD_PRELOAD=/usr/local/lib/faketime/libfaketime.so.1
ENV FAKETIME_NO_CACHE=1
CMD gpg --with-colons …
```
=> PP-10892: Only check for key expiry

logging-dropwizard-3/pom.xml, logging-dropwizard-3/src/main/java/uk/gov/service/payments/logging/SentryAppenderFactory.java
The [SentryAppenderFactory for dropwizard-sentry
2.1.6](https://github.com/dhatim/dropwizard-sentry/blob/2.1.6/src/main/java/org/dhatim/dropwizard/sentry/logging/SentryAppenderFactory.java) doesn't work because the `io.dropwizard.logging` imports are outdated and have moved to `io.dropwizard.logging.common`. Interestingly there is no [dropwizard-sentry library for dropwizard
3](https://mvnrepository.com/artifact/org.dhatim/dropwizard-sentry). So unfortunately we have to copy the SentryAppenderFactory from dropwizard-sentry 2.1.6 and use the updated dropwizard 3 imports.
Unfortunately we cannot use version 4 of `org.dhatim/dropwizard-sentry` as it uses a `jakarta.validation.constraints.NotNull` import which we don't have (or would require another dependency in our java apps).
I created a …
=> bau: Add sentry appender factory for dropwizard 3.x logging support

model/src/main/java/uk/gov/service/payments/commons/model/CardExpiryDate.java, model/src/test/java/uk/gov/service/payments/commons/model/CardExpiryDateTest.java
- Add valueOf and constructor to allow CardExpiryDate to be created from YearMonth
- This supports extraction of expiry date from Worldpay response to wallet authorisations
=> PP-11465-Create-CardExpiryDate-from-YearMonth

.github/workflows/build-and-publish.yml
Currently it's very hard to understand what is in each release since they are only recorded in maven. It also means dependabot cannot generate helpful update messages in the dependent repos.
Create a github release in this repo whenever we publish to maven.
=> PP-11548: Create a github release when we release to maven

.github/workflows/build-and-publish.yml
Minor oops. The first release created by this workflow had the literal name `Release $PACKAGE_VERSION`.
This change uses the correct github output instead of assuming it's in the env.
=> PP-11548: Fix release name in createRelease step

.github/dependabot.yml
Ignore some versions of Maven dependencies we cannot upgrade to in Dependabot configuration.
Also fix problems reported by `yamllint`.
=> PP-12520 Ignore some Maven dependency versions in Dependabot config

.github/dependabot.yml
There are POM files in various subdirectories and Dependabot ignores are not, generally speaking, applied recursively.
THis adds some annoying duplication because there is no way to specify multiple directories in the directory option.
=> PP-125020 Apply Dependabot ignores correctly to subdirectories

.github/dependabot.yml
Just two dashes actually makes the file invalid YAML and stops it from being parsed.
=> PP-12520 Change two dashes to three to fix Dependabot config file

.github/dependabot.yml
dependabot is dumb enough as not to inherit the ignore setings from the parent module. It tries to upgrade the parent module on top of that.
- add ignore DW 4 to all child modules
=> PP-12177 add ignore Dropwizard 4 to all child modules

.github/dependabot.yml
We no longer explicitly specify Hibernate Validator's version number
- remove ignore for Hibernate Validator
=> PP-12177 fine tune dependabot config 2

model/src/main/java/uk/gov/service/payments/commons/api/validation/AllowedStrings.java, model/src/main/java/uk/gov/service/payments/commons/api/validation/AllowedStringsValidator.java
Moving from [pay-connector](https://github.com/alphagov/pay-connector/blob/master/src/main/java/uk/gov/pay/connector/util/validation/AllowedStrings.java) as this validator would be useful for other java projects.
=> bau: Move AllowedString constraint to pay-java-commons

model/src/main/java/uk/gov/service/payments/commons/api/json/ApiResponseDateTimeSerializer.java, model/src/main/java/uk/gov/service/payments/commons/api/json/IsoInstantMicrosecondDeserializer.java, model/src/main/java/uk/gov/service/payments/commons/api/json/IsoInstantMicrosecondSerializer.java, model/src/main/java/uk/gov/service/payments/commons/api/json/IsoInstantMillisecondDeserializer.java, model/src/main/java/uk/gov/service/payments/commons/api/json/IsoInstantMillisecondSerializer.java, model/src/main/java/uk/gov/service/payments/commons/model/CommonDateTimeFormatters.java, model/src/test/java/uk/gov/service/payments/commons/api/json/IsoInstantMicrosecondDeserializerTest.java, model/src/test/java/uk/gov/service/payments/commons/api/json/IsoInstantMicrosecondSerializerTest.java, model/src/test/java/uk/gov/service/payments/commons/api/json/IsoInstantMillisecondDeserializerTest.java, model/src/test/java/uk/gov/service/payments/commons/api/json/IsoInstantMillisecondSerializerTest.java, model/src/test/java/uk/gov/service/payments/commons/model/CommonDateTimeFormattersTest.java
- Rename `ApiResponseDateTimeFormatter` to `CommonDateTimeFormatters` since it’s not just used for API responses
- Rename `ApiResponseInstantSerializer` to `IsoInstantMillisecondSerializer` because it’s not just used for API responses and to reflect it has millisecond precision
- Rename `ApiResponseInstantWithMicrosecondPrecisionSerializer` to `IsoInstantMicrosecondSerializer` because it’s not just used for API responses
- Add `IsoInstantMillisecondDeserializer` and `IsoInstantMicrosecondDeserializer` — these parse ISO instant strings into `Instant` objects and are strict about how any decimal places are required for the seconds (three for millisecond and six for microsecond)
=> PP-13220 Better consistency for Instant serialisers/deserialisers

.github/workflows/build-and-publish.yml, .github/workflows/run-tests.yml
Upgrades the following to run on Node 20:
`actions/checkout`
`actions/setup-java`
`actions/cache`
`actions/github-script`
=> PP-12244: Upgrade deprecated Github Actions

README.md
Adds missing sections to the repo README.
Text based on the [pay-frontend README](https://github.com/alphagov/pay-frontend?tab=readme-ov-file#licence).
=> BAU: Add missing Licence and Vulnerability Disclosure to README

.github/workflows/build-and-publish.yml, .github/workflows/run-tests.yml
Github deprecated the version of actions/cache we were using. [We need to upgrade to v4.2.0](https://github.com/actions/cache/releases/tag/v4.2.0).
=> BAU: Update deprecated actions/cache to v4.2.0

pom.xml, queue-java-aws-sdk-v2/pom.xml, queue-java-aws-sdk-v2/src/main/java/uk/gov/service/payments/commons/queue/exception/QueueException.java, queue-java-aws-sdk-v2/src/main/java/uk/gov/service/payments/commons/queue/model/QueueMessage.java, queue-java-aws-sdk-v2/src/main/java/uk/gov/service/payments/commons/queue/sqs/AbstractQueue.java, queue-java-aws-sdk-v2/src/main/java/uk/gov/service/payments/commons/queue/sqs/SqsQueueService.java, queue-java-aws-sdk-v2/src/test/java/uk/gov/service/payments/commons/queue/sqs/SqsQueueServiceTest.java
The AWS SDK for Java 1.x is in maintenance mode, effective July 31, 2024.
The AWS SDK for Java 1.x will no longer receive updates for new or existing services
The 1.x SDK will continue to receive critical bug fixes and security updates until December 31, 2025.
AWS recommend that we move to the java 2.x versions of the aws sdk
=> PP-13575 Investigate java AWS SDK v2 upgrade

.github/workflows/build-and-publish.yml, pom.xml
- migrate deployment plugin from ossrh to central publishing portal
- streamline `build_and_publish` action
- move env values to job level to reduce repetition
- delete env var declaration in release step as it is now defined at the job level
- remove separate cache step, prefer cache configuration in actions/setup-java
=> PP-14301 migrate to central publishing portal

.github/workflows/build-and-publish.yml, pom.xml
- bump action to `4.7.1`
- give maven central deployment a sensible name
=> PP-14301 upgrade actions/setup-java
